name: deploy_service

on:
  push: # ì›Œí¬í”Œë¡œìš° ì‹¤í–‰ ì¡°ê±´ ì´ë²¤íŠ¸
    branches: # ì›Œí¬í”Œë¡œìš° ì‹¤í–‰ ì¡°ê±´ ë¸Œëœì¹˜
      - main

jobs:
  ssh-agent: # job ì´ë¦„ë¦„
    runs-on: ubuntu-24.04 # github ì›Œí¬ìŠ¤í˜ì´ìŠ¤ í™˜ê²½

    steps: # ì‹¤í–‰í•  ì‘ì—…(step)
      - name: Checkout code
        uses: actions/checkout@v4.2.2

      - name: Start Message
        uses: sarisia/actions-status-discord@v1
        with:
          webhook: ${{secrets.DISCORD_WEBHOOK}}
          title: "ğŸ‡ğŸš€ ë°°í¬ ì‹œì‘ ğŸ‡ğŸš€"

      # ìºì‹œ ì €ì¥ ì„¤ì •ì„ ìœ„í•œ action(ë¼ì´ë¸ŒëŸ¬ë¦¬)
      - name: Cache Docker Image Layer
      # actions/cache: ê¹ƒí—ˆë¸Œ ìºì‹œ ì €ì¥ì†Œ í™œìš©ì„ ìœ„í•œ ë¼ì´ë¸ŒëŸ¬ë¦¬
        uses: actions/cache@v4.2.0
        with:
          path: /tmp/.buildx-cache
          key: docker-image-layer-cache-${{github.sha}}
          restore-keys: docker-image-layer-cache-
            #d


      - name: run ssh-agent
        uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY  }}

          # ì›ê²© ì„œë²„ë¥¼ ì‹ ë¢°í•  ìˆ˜ ìˆëŠ” ì„œë²„ë¡œ ë“±ë¡í•˜ëŠ” ê³¼ì •.
          # known_hosts : ì›ê²© ì„œë²„ë“¤ì˜ ì§€ë¬¸ì´ ì €ì¥ëœ íŒŒì¼
      - name: Add Remote Server Fingerprint to known Hosts
        run: ssh-keyscan -H -p ${{secrets.SSH_PORT}} ${{secrets.SSH_HOST}} >> ~/.ssh/known_hosts || true

      - name: Create .env file
        run: |
          echo "DATABASE_HOST=${{ secrets.DATABASE_HOST }}" >> .env
          echo "DATABASE_NAME=${{ secrets.DATABASE_NAME }}" >> .env
          echo "DATABASE_PASSWORD=${{ secrets.DATABASE_PASSWORD }}" >> .env
          echo "DATABASE_PORT=${{ secrets.DATABASE_PORT }}" >> .env
          echo "DATABASE_USERNAME=${{ secrets.DATABASE_USERNAME }}" >> .env
          echo "MYSQL_DATABASE=${{ secrets.MYSQL_DATABASE }}" >> .env
          echo "MYSQL_ROOT_PASSWORD=${{ secrets.MYSQL_ROOT_PASSWORD }}" >> .env
          echo "VITE_API_URL=${{ secrets.VITE_API_URL }}" >> .env


# ë„ì»¤ Buildkit ì—”ì§„ ì„¤ì • action(ë¼ì´ë¸ŒëŸ¬ë¦¬)
      - name: Set up Docker Buildkit
      # setup-buildx-action
      # -Buildkitì„ ì„¤ì¹˜í•˜ëŠ” actino(ë¼ì´ë¸ŒëŸ¬ë¦¬)
      # buildx = Buildkit
        uses: docker/setup-buildx-action@v3

  # Buildkit ì—”ì§„ ë¹Œë”(ì´ë¯¸ì§€ ë¹Œë“œë¥¼ ë„ì™€ì£¼ëŠ” ë„êµ¬) ìƒì„±
  # ê¸°ì¡´ Docker ë¹Œë” : Cache íŒŒì¼ ì €ì¥&ë¶ˆëŸ¬ì˜¤ëŠ” ê²½ë¡œ ì œì–´ ë¶ˆê°€
      - name: Create Buildkit ë¹Œë”
      # 1. buildkit ë¹Œë”(buildkit)ë¥¼ ìƒì„±í•˜ëŠ” ëª…ë ¹ì–´
      # 2. ë¹Œë”(buildkit) ì„¤ì • ëª…ë ¹ì–´
        run: |
          docker buildx create --use --name buildkit
          docker buildx use buildkit

      - name: Docker Image Build
        run: docker compose -f docker-compose-actions-cache.yml build --build-arg BUILDKIT_INLINE_CACHE=1

      - name: Login DockerHub
        run: echo '${{secrets.DOCKER_PASSWORD}}' | docker login -u '${{secrets.DOCKER_USERNAME}}' --password-stdin

      - name: Docker Image Push
        run: docker compose -f docker-compose-actions-cache.yml push

      - name: Copy .env / docker-compose-action-cache.yml
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{secrets.SSH_HOST}}
          username: ${{ secrets.SSH_USERNAME}}
          key: ${{secrets.SSH_PRIVATE_KEY}}
          port: ${{ secrets.SSH_PORT}}
          source: 'docker-compose-actions-cache.yml,.env'
          target: '~/work-directory'

      - name: Pull Image & Up Container
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{secrets.SSH_HOST}}
          username: ${{ secrets.SSH_USERNAME}}
          key: ${{secrets.SSH_PRIVATE_KEY}}
          port: ${{ secrets.SSH_PORT}}
          script: |
            cd ~/work-directory
            docker-compose -f docker-compose-actions-cache.yml pull
            docker-compose -f docker-compose-actions-cache.yml down
            docker-compose -f docker-compose-actions-cache.yml up -d
            docker image prune -f
      - name: End Message - Success
        uses: sarisia/actions-status-discord@v1
        if: success()
        with:
          webhook: ${{secrets.DISCORD_WEBHOOK}}
          title: "ë°°í¬ ì¢…ë£Œ - ğŸ‰ì„±ê³µğŸ‰"

      - name: End Message -Fail
        uses: sarisia/actions-status-discord@v1
        if: failure()
        with:
          webhook: ${{secrets.DISCORD_WEBHOOK}}
          title: "ë°°í¬ ì¢…ë£Œ - ğŸ¤¯ì‹¤íŒ¨ğŸ¤¯"