name: deploy_service

on:
  push: # ì›Œí¬í”Œë¡œìš° ì‹¤í–‰ ì¡°ê±´ ì´ë²¤íŠ¸
    branches: # ì›Œí¬í”Œë¡œìš° ì‹¤í–‰ ì¡°ê±´ ë¸Œëžœì¹˜
      - main

jobs:
  ssh-agent: # job ì´ë¦„ë¦„
    runs-on: ubuntu-24.04 # github ì›Œí¬ìŠ¤íŽ˜ì´ìŠ¤ í™˜ê²½

    steps: # ì‹¤í–‰í•  ìž‘ì—…(step)
      - name: Checkout code
        uses: actions/checkout@v4.2.2

      - name: Start Message
        uses: sarisia/actions-status-discord@v1
        with:
          webhook: ${{secrets.DISCORD_WEBHOOK}}
          title: "ðŸŽ‡ðŸš€ ë°°í¬ ì‹œìž‘"

      - name: run ssh-agent
        uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY  }}

          # ì›ê²© ì„œë²„ë¥¼ ì‹ ë¢°í•  ìˆ˜ ìžˆëŠ” ì„œë²„ë¡œ ë“±ë¡í•˜ëŠ” ê³¼ì •.
          # known_hosts : ì›ê²© ì„œë²„ë“¤ì˜ ì§€ë¬¸ì´ ì €ìž¥ëœ íŒŒì¼
      - name: Add Remote Server Fingerprint to known Hosts
        run: ssh-keyscan -H -p ${{secrets.SSH_PORT}} ${{secrets.SSH_HOST}} >> ~/.ssh/known_hosts || true

      - name: Create .env file
        run: |
          echo "DATABASE_HOST=${{ secrets.DATABASE_HOST }}" >> .env
          echo "DATABASE_NAME=${{ secrets.DATABASE_NAME }}" >> .env
          echo "DATABASE_PASSWORD=${{ secrets.DATABASE_PASSWORD }}" >> .env
          echo "DATABASE_PORT=${{ secrets.DATABASE_PORT }}" >> .env
          echo "DATABASE_USERNAME=${{ secrets.DATABASE_USERNAME }}" >> .env
          echo "MYSQL_DATABASE=${{ secrets.MYSQL_DATABASE }}" >> .env
          echo "MYSQL_ROOT_PASSWORD=${{ secrets.MYSQL_ROOT_PASSWORD }}" >> .env
          echo "VITE_API_URL=${{ secrets.VITE_API_URL }}" >> .env

      - name: Docker Image Build
        run: docker compose build

      - name: Login DockerHub
        run: echo '${{secrets.DOCKER_PASSWORD}}' | docker login -u '${{secrets.DOCKER_USERNAME}}' --password-stdin

      - name: Docker Image Push
        run: docker compose push

      - name: Copy .env / docker-compose.yml
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{secrets.SSH_HOST}}
          username: ${{ secrets.SSH_USERNAME}}
          key: ${{secrets.SSH_PRIVATE_KEY}}
          port: ${{ secrets.SSH_PORT}}
          source: 'docker-compose.yml,.env'
          target: '~/work-directory'

      - name: Pull Image & Up Container
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{secrets.SSH_HOST}}
          username: ${{ secrets.SSH_USERNAME}}
          key: ${{secrets.SSH_PRIVATE_KEY}}
          port: ${{ secrets.SSH_PORT}}
          script: |
            cd ~/work-directory
            docker-compose pull
            docker-compose down
            docker-compose up -d
